### ISSUE TITLE
Radio button dot does not appear immediately on first click

### ISSUE THREAD

**Issue by oliver3** [kiesraad/abacus#454]
When you first select a radio button on a page, for instance on the "Is er herteld?" page, there is a delay before the dot inside the radio button is shown.

This seems to be because the `dot.svg` has to be retrieved over the network.

https://css-tricks.com/images-in-postcss/ mentions some (older?) options that we could have a look at.

**Comment by praseodym** [comment]
Can you also reproduce this with the production build? On https://kiesraad-abacus.pages.dev the `dot.svg` appears to be embedded in the CSS directly, so there is no network overhead:

```css
/* Set radio icon */
[type="radio"]:is(._checkbox-and-radio_2ooi1_13 input):checked::before {
      -webkit-mask-image: url("data:image/svg+xml,%3csvg%20viewBox='0%200%2024%2024'%20role='img'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M11.9999%2018.6667C15.6818%2018.6667%2018.6666%2015.6819%2018.6666%2012C18.6666%208.31811%2015.6818%205.33334%2011.9999%205.33334C8.31802%205.33334%205.33325%208.31811%205.33325%2012C5.33325%2015.6819%208.31802%2018.6667%2011.9999%2018.6667Z'%20/%3e%3c/svg%3e");
              mask-image: url("data:image/svg+xml,%3csvg%20viewBox='0%200%2024%2024'%20role='img'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M11.9999%2018.6667C15.6818%2018.6667%2018.6666%2015.6819%2018.6666%2012C18.6666%208.31811%2015.6818%205.33334%2011.9999%205.33334C8.31802%205.33334%205.33325%208.31811%205.33325%2012C5.33325%2015.6819%208.31802%2018.6667%2011.9999%2018.6667Z'%20/%3e%3c/svg%3e");
    }
/* Set checkbox icon */
[type="checkbox"]:is(._checkbox-and-radio_2ooi1_13 input):checked::before {
      -webkit-mask-image: url("data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/2000/svg'%20version='1.1'%20viewBox='0%200%2014%2014'%20role='img'%3e%3cpath%20d='M5.2,10.9h0c-.3,0-.5-.1-.7-.3l-2.9-2.9c-.4-.4-.4-1,0-1.4.4-.4,1-.4,1.4,0l2.2,2.2,5.7-5.7c.4-.4,1-.4,1.4,0s.4,1,0,1.4l-6.4,6.4c-.2.2-.4.3-.7.3Z'/%3e%3c/svg%3e");
              mask-image: url("data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/2000/svg'%20version='1.1'%20viewBox='0%200%2014%2014'%20role='img'%3e%3cpath%20d='M5.2,10.9h0c-.3,0-.5-.1-.7-.3l-2.9-2.9c-.4-.4-.4-1,0-1.4.4-.4,1-.4,1.4,0l2.2,2.2,5.7-5.7c.4-.4,1-.4,1.4,0s.4,1,0,1.4l-6.4,6.4c-.2.2-.4.3-.7.3Z'/%3e%3c/svg%3e");
    }
```

(I think this is done by Vite, which has some smart [static asset handling](https://vite.dev/guide/assets)).
